CREATE TABLE IF NOT EXISTS USERS
(
    "ID"   UUID PRIMARY KEY,
    "NAME" VARCHAR2(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BATTLES
(
    ID            UUID PRIMARY KEY,
    Player1       UUID         NOT NULL,
    Player2       UUID         NOT NULL,
    Status        VARCHAR2(30) NOT NULL,
    ShooterPlayer UUID         NOT NULL,
    Winner        UUID         NULL,
    CONSTRAINT FK_PLAYER_1 FOREIGN KEY (Player1) REFERENCES USERS,
    CONSTRAINT FK_PLAYER_2 FOREIGN KEY (Player2) REFERENCES USERS,
    CONSTRAINT FK_SHOOTER FOREIGN KEY (ShooterPlayer) REFERENCES USERS,
    CONSTRAINT FK_WINNER FOREIGN KEY (Winner) REFERENCES USERS
);

CREATE TABLE IF NOT EXISTS FLEETS
(
    BattleId UUID          NOT NULL,
    PlayerId UUID          NOT NULL,
    Status   VARCHAR2(30)  NOT NULL,
    Shots    VARCHAR2(200) NOT NULL,
    PRIMARY KEY (BattleId, PlayerId),
    CONSTRAINT FK_BATTLE_ID FOREIGN KEY (BattleId) REFERENCES BATTLES,
    CONSTRAINT FK_PLAYER_ID FOREIGN KEY (PlayerId) REFERENCES USERS
);

CREATE TABLE IF NOT EXISTS SHIPS
(
    BattleId    UUID         NOT NULL,
    PlayerId    UUID         NOT NULL,
    Type        VARCHAR2(30) NOT NULL,
    Status      VARCHAR2(30) NOT NULL,
    Origin      VARCHAR2(2)  NOT NULL,
    Orientation VARCHAR2(30) NOT NULL,
    Hits        VARCHAR2(10)  NOT NULL,
    PRIMARY KEY (BattleId, PlayerId, Type),
    CONSTRAINT FK_BATTLE_ID_2 FOREIGN KEY (BattleId) REFERENCES BATTLES,
    CONSTRAINT FK_PLAYER_ID_2 FOREIGN KEY (PlayerId) REFERENCES USERS
);
