openapi: 3.0.3
info:
  title: Battleship Player API
  description: Battleship Player API
  version: 1.0.0
servers:
  - url: 'http://localhost:11000/battleship'
components:
  schemas:
    player:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
paths:
  /players:
    get:
      description: "Get all available players in the server"
      responses:
        '200':
          description: "A list of players"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/player'

